# Production image for Railway (or any Docker host). Serves static Astro `dist/` + GET /health.
# Bake homepage URLs at build: pass the same PUBLIC_* names as `.env` (Railway Variables / `docker build --build-arg`).
FROM node:22-alpine AS build
WORKDIR /app
ARG PUBLIC_STANDARD_REPO_URL=""
ARG PUBLIC_MCP_REPO_URL=""
ARG PUBLIC_MCP_QUICKSTART_URL=""
ARG PUBLIC_MCP_CUSTOMER_DOCS_URL=""
ARG PUBLIC_CLERK_SIGN_IN_URL=""
ARG PUBLIC_CLERK_SIGN_UP_URL=""
ARG PUBLIC_CLERK_USER_PROFILE_URL=""
ARG PUBLIC_CLERK_SIGN_OUT_URL=""
ARG PUBLIC_CLERK_PUBLISHABLE_KEY=""
ARG PUBLIC_CLERK_SATELLITE_DOMAIN=""
ENV PUBLIC_STANDARD_REPO_URL=$PUBLIC_STANDARD_REPO_URL \
	PUBLIC_MCP_REPO_URL=$PUBLIC_MCP_REPO_URL \
	PUBLIC_MCP_QUICKSTART_URL=$PUBLIC_MCP_QUICKSTART_URL \
	PUBLIC_MCP_CUSTOMER_DOCS_URL=$PUBLIC_MCP_CUSTOMER_DOCS_URL \
	PUBLIC_CLERK_SIGN_IN_URL=$PUBLIC_CLERK_SIGN_IN_URL \
	PUBLIC_CLERK_SIGN_UP_URL=$PUBLIC_CLERK_SIGN_UP_URL \
	PUBLIC_CLERK_USER_PROFILE_URL=$PUBLIC_CLERK_USER_PROFILE_URL \
	PUBLIC_CLERK_SIGN_OUT_URL=$PUBLIC_CLERK_SIGN_OUT_URL \
	PUBLIC_CLERK_PUBLISHABLE_KEY=$PUBLIC_CLERK_PUBLISHABLE_KEY \
	PUBLIC_CLERK_SATELLITE_DOMAIN=$PUBLIC_CLERK_SATELLITE_DOMAIN
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8080
COPY --from=build --chown=node:node /app/dist ./dist
COPY --chown=node:node scripts/docker-serve.mjs ./serve.mjs
EXPOSE 8080
USER node
CMD ["node", "serve.mjs"]
